site_name: Annonce

nav:
  - Description: index.md
  - Photos: 
    - Salon: salon.md
    - Chambre: chambre.md
    - Balcon: balcon.md
    - Cuisine: cuisine.md
    - Salle de bain: sdb.md
    - Sanitaires: wc.md
    - Entrée: entree.md
  - Contact: contact.md

theme:
  name: 'minty'